version: '2.1'
services:
  ganache:
    image: trufflesuite/ganache-cli:v6.10.1
    ports:
      - "8545:8545"
    # Nota Bene - the mnemonic below is *INSECURE* and shouldn't be used for real funds, only local development
    #             it serves only to create deterministic accounts that can be shared with metamask
    command: ganache-cli --mnemonic "album wire record stuff abandon mesh museum piece bean allow refuse below"
  ganache-deploy:
    build:
      #context: ./ethereum
      context: ./merkle
      dockerfile: Dockerfile
    healthcheck:
      test: curl -sf -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' http://ganache:8545
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./ethereum/build:/usr/src/app/build
